# Generated by Django 3.1.6 on 2021-02-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvfileinside', '0002_auto_20210222_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
    ]
