# Generated by Django 3.1.1 on 2021-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfileinside', '0002_auto_20210308_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Sales_Proportion',
            field=models.TextField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Stock_Proportion',
            field=models.TextField(max_length=8, null=True),
        ),
    ]
