# Generated by Django 3.1.1 on 2021-03-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfileinside', '0003_auto_20210309_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse', models.TextField(max_length=200, null=True)),
                ('Warehouse_ID', models.TextField(max_length=20, null=True)),
                ('Sales_Volume', models.TextField(max_length=20, null=True)),
                ('Sales_Proportion', models.TextField(max_length=20)),
                ('All_Stock', models.TextField(max_length=20)),
                ('Stock_Proportion', models.TextField(max_length=20)),
                ('Average_Flow', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('Turnover_Days', models.IntegerField(max_length=10)),
            ],
        ),
    ]
