# Generated by Django 3.1.7 on 2021-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfileinside', '0004_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Turnover_Days',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
