# Generated by Django 3.1.7 on 2021-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfileinside', '0008_auto_20210319_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='Turnover_Days',
            field=models.IntegerField(null=True),
        ),
    ]
